apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-local-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /opt/grafana/data # Adjust the path to where the storage is located on the nodes
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - master1
            - worker1
            - worker2

